from __future__ import annotations

from vstacklens.deep.contracts import ThresholdPolicy, ThresholdRegistry


def default_threshold_registry() -> ThresholdRegistry:
    """Return the reviewed v1 policy set; values are never embedded in analyzers."""

    return ThresholdRegistry(
        policies=[
            ThresholdPolicy(
                id="TH-EVIDENCE-COMPLETENESS-MIN",
                value=0.8,
                unit="ratio",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Evidence completeness below this level cannot independently support a customer finding.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-TREND-DAILY-GROWTH",
                value=0.5,
                unit="percent_per_day",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="A sustained daily capacity increase at or above this level is a reviewable statistical trend.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-DATASTORE-USED-PERCENT-HIGH",
                value=80.0,
                unit="percent",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="A datastore at or above this utilization requires capacity review before further growth.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-VM-COUNT-DAILY-GROWTH",
                value=1.0,
                unit="count_per_day",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="持续每天新增至少一个虚拟机需要结合容量、许可和治理计划复核。",
                last_reviewed="2026-09-23",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-THIN-PROVISION-GROWTH",
                value=0.05,
                unit="ratio_per_day",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Thin Provision 比例持续每日增长达到 0.05 需要结合容量和业务增长计划复核。",
                last_reviewed="2026-09-23",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-SNAPSHOT-CHAIN-DEPTH",
                value=3.0,
                unit="level",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="A snapshot chain at or above this depth requires a manual consolidation and business-retention review.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-THIN-PROVISION-RATIO",
                value=1.5,
                unit="ratio",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Datastore virtual capacity at or above 1.5 times physical capacity requires thin-provisioning review.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-LIFECYCLE-EXPIRY-WINDOW",
                value=60.0,
                unit="day",
                comparator="<=",
                source="vstacklens_engineering",
                rationale="管理证书或评估/订阅许可在到期前 60 天进入复核窗口；已过期对象同样需要复核。该窗口用于提示排期，不替代客户续期流程。",
                last_reviewed="2026-09-28",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-NET-LINK-FLAP-STATE-CHANGES",
                value=3.0,
                unit="state_changes",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Only repeated up/down oscillation is classified as a link flap; a single link-down event is kept under network error history. This is an engineering default, not a vendor threshold.",
                last_reviewed="2026-09-26",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-NET-LINK-FLAP-WINDOW-SECONDS",
                value=900.0,
                unit="seconds",
                comparator="<=",
                source="vstacklens_engineering",
                rationale="The default 15-minute window screens for repeated transitions occurring close together. This is an engineering default, not a vendor threshold.",
                last_reviewed="2026-09-26",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-CPU-READY-HIGH",
                value=5.0,
                unit="percent",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Sustained CPU Ready at or above 5 percent requires scheduling and workload review.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-CPU-USAGE-HIGH",
                value=90.0,
                unit="percent",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Sustained host CPU utilization at or above 90 percent requires workload and scheduling review.",
                last_reviewed="2026-09-23",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-CPU-COSTOP-HIGH",
                value=3.0,
                unit="percent",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Sustained CPU Co-stop at or above 3 percent requires VM SMP sizing and host scheduling review.",
                last_reviewed="2026-09-23",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-STORAGE-LATENCY-HIGH",
                value=20.0,
                unit="millisecond",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Sustained storage latency at or above 20 milliseconds requires storage-path and array review.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-MEMORY-BALLOON-HIGH",
                value=1024.0,
                unit="megabyte",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="Sustained ballooning at or above 1 GB requires host memory contention and workload review.",
                last_reviewed="2026-09-23",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-VSAN-CAPACITY-HIGH",
                value=80.0,
                unit="percent",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="A vSAN datastore at or above this utilization requires capacity and resync review.",
                last_reviewed="2026-09-21",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
            ThresholdPolicy(
                id="TH-VSAN-CONGESTION-HIGH",
                value=1.0,
                unit="count",
                comparator=">=",
                source="vstacklens_engineering",
                rationale="A non-zero vSAN congestion sample requires workload, disk-group, and resync correlation.",
                last_reviewed="2026-09-23",
                reviewed_by="VStackLens engineering",
                overridable=True,
            ),
        ]
    )
